name: Release Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release_web:
    name: Web Release
    runs-on: ubuntu-latest

    steps:
      - name: Add submodule
        run: git submodule update --init --recursive
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: ./build.sh -b Release -e OFF